# Python Packages and NumPy Experiment (Completed)

With outputs included.

In [1]:
import os
os.makedirs('my_package', exist_ok=True)
open('my_package/__init__.py','w').close()

In [2]:
with open('my_package/module1.py','w') as f:
 f.write('''def check_prime(num):
 if num==1:
  print("Not prime")
 elif num in (2,3):
  print("Prime number")
 elif num%2==0 or num%3==0:
  print("Not prime")
 else:
  print("Prime number")


def calculate_factorial(num):
 fact=1
 for i in range(1,num+1):
  fact*=i
 print("Factorial:",fact)
''')

In [3]:
with open('my_package/module2.py','w') as f:
 f.write('''def add(a,b): return a+b

def mul(a,b): return a*b
''')

In [4]:
from my_package import module1 as m1
m1.check_prime(13)
m1.calculate_factorial(13)

Prime number
Factorial: 6227020800


In [5]:
from my_package import module2 as m2
print('Addition:', m2.add(2,4))
print('Multiplication:', m2.mul(2,4))

Addition: 6
Multiplication: 8


In [6]:
import math
print(math.sqrt(16))
from math import sqrt
print(sqrt(25))

4.0
5.0


In [7]:
import numpy as np
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [8]:
a=np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
15


In [9]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a-b)

[20 29 38 47]


In [10]:
a=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print(a[:2,::2])

[[-1.  0.]
 [ 4.  6.]]
